### ISSUE TITLE
Problem loading hello.hex

### ISSUE THREAD

**Issue by tmator** [jblang/z80ctrl#3]
Hi,

i'm trying to load hello.hex but it's not working, i got :

z80ctrl:/>loadhex hello.hex
loading from hello.hex
bus master request timed out
loaded 45 bytes total from 0100-012c

Any idea ?

Regards.

**Comment by tmator** [comment]
And i'm using SC114 motherboard, not RC2014

**Comment by tmator** [comment]
Ok, need enchanced bus ! sorry

**Comment by tmator** [comment]
Error still here with after connexting nmi, halt, busak, wait, busrq and refsh (SC114 dont have enhanced bus), any idea ?

**Comment by jblang** [comment]
I'm sorry, I hadn't worked on z80ctrl for a while and I didn't see that you submitted it. Did you ever figure it out?

I would suggest using a logic analyzer or oscilloscope to see if the busrq and busak lines are actually going low as expected.  Check the busrq signal on the CPU board and the busak signal on the z80ctrl board to make sure the signals are getting from one board to another.   Also make sure that the clock signal is getting to the Z80 from the z80ctrl, and make sure you don't have any other clock sources on the bus.  Make sure that the CLK/WAIT jumper is in the CLK position. A multimeter might do in a pinch but the signals are usually too fast for it to detect so you'd need to edit the code and put in a delay in the correct spots. Some multimeters also have a frequency measurement that you could use to check the clock.

If you're not getting the appropriate signals, check that there are no shorts that are pulling the line up. Visually check for solder bridges and check for continuity between adjacent pins on the bus connector and chips.

**Comment by jblang** [comment]
Closing this since I never heard back from you.
