### ISSUE TITLE
where is the J9  description in REV4 and REV6 ?

### ISSUE THREAD

**Issue by wenij** [jblang/z80ctrl#7]
I check the "Board Assembly instruction/Jumper configuration" in wiki. And in REV6, it say "J9 (CLK/WAIT) jumper ... ", but I can't find the J9 in the PCB or schematic. Where can I find it?

**Comment by jblang** [comment]
There is no CLK/WAIT jumper in REV6.  On REV4 it should always be set to CLK

**Comment by jblang** [comment]
It was a copy/paste error that it was listed under REV6. I removed it.
